### PR TITLE
Adding ability to highlight YAML

### PR DESCRIPTION
**Pull request by pzach001**
Wanted to add the ability to support YAML.
I did this by:
1. Added YAML as an option in the menubar in index.html
2. I  updated highlight.pack.js by getting a  version of the file that included YAML support  from highlight.js's website(https://highlightjs.org/download/).

### CODE REVIEW

**Comment by Savjee** [comment]
Look really good! I'll submit it to the Mac App Store and keep you posted ;)
Thanks a lot!

**Comment by pzach001** [comment]
Sweet! Thank you so  much!

**Comment by Savjee** [comment]
Submitted to the App Store! Waiting for review...

**Comment by Savjee** [comment]
It's in review...........

**Comment by Savjee** [comment]
Live! Thanks again!

**Pull request merged**
